name: Semgrep Scan

on:
  # Scan on push to main branch
  push:
    branches: [ "master" ]
  # Scan on PRs to main branch
  pull_request:
    branches: [ "master" ]

jobs:
  semgrep:
    name: Semgrep Code Scan
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@v3
    
    - name: Run Semgrep
      run: |
        mkdir -p semgrep/results
        semgrep ci --config=auto --sarif --output=semgrep/results/semgrep.sarif || true
        
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: semgrep.sarif

    - name: Upload Semgrep report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: semgrep-results
        path: semgrep/results/
